Repository apache/pulsar-site, pull requests merged in 2023-12, with the labels that each got.

#744 Release 3.0.2
  data/release-java.js
  data/release-pulsar.js
  release-notes/versioned/client-java-3.0.2.md
  release-notes/versioned/pulsar-3.0.2.md
  static/swagger/3.0.2/swagger.json
  static/swagger/3.0.2/swaggerfunctions.json
  static/swagger/3.0.2/swaggerlookup.json
  static/swagger/3.0.2/swaggerpackages.json
  static/swagger/3.0.2/swaggersink.json
  static/swagger/3.0.2/swaggersource.json
  static/swagger/3.0.2/swaggertransactions.json
  static/swagger/3.0.2/v2/swagger.json
  static/swagger/3.0.2/v2/swaggerlookup.json
  static/swagger/3.0.2/v3/swaggerfunctions.json
  static/swagger/3.0.2/v3/swaggerpackages.json
  static/swagger/3.0.2/v3/swaggersink.json
  static/swagger/3.0.2/v3/swaggersource.json
  static/swagger/3.0.2/v3/swaggertransactions.json
  static/swagger/restApiVersions.json
Labels: doc

#746 Fix the release tables for 3.0.2
  data/release-pulsar.js
Labels: doc

#743 [fix][doc] Add missing space in sentence
  docs/concepts-broker-load-balancing-concepts.md
Labels: doc

#747 [improve][doc]Add athenz copper argos sample code in python/nodejs
  docs/security-athenz.md
Labels: doc

#749 [improve][doc] Implementing documentation for debugging Pulsar source code
  contribute/setup-debugging.md
  sidebarsDevelopment.js
Labels: doc

#751 Specify Maven wrapper in setup-building.md
  contribute/setup-building.md
Labels: doc

#750 Improve GPG instructions in the contribution guide
  contribute/create-gpg-keys.md
Labels: doc-not-needed

#752 Contribution guide: Add step for importing the committer's public GPG key from the key server
  contribute/create-gpg-keys.md
Labels: doc

#753 Add the release note for C++ client 3.4.2
  data/release-cpp.js
  release-notes/versioned/client-cpp-3.4.2.md
Labels: doc

#754 [doc][client feature matrix] improve experience for .NET users looking for information on .NET/C# clients
  client-feature-matrix/index.mdx
  data/matrix.js
  docs/client-libraries.md
  src/components/Matrix/util.js
Labels: doc

#757 [improve][misc] ASF branding
  docs/about.md
  src/components/pages/HomePage/ShortInfo/ShortInfo.tsx
  src/pages/download.mdx
  versioned_docs/version-2.10.x/about.md
  versioned_docs/version-2.11.x/about.md
  versioned_docs/version-2.8.x/about.md
  versioned_docs/version-2.9.x/about.md
  versioned_docs/version-3.0.x/about.md
  versioned_docs/version-3.1.x/about.md
Labels: doc-complete
